# Configuration GitHub Sponsors (optionnel)
# Décommenter et configurer si vous voulez accepter des sponsorships

# github: [VOTRE-USERNAME]
# patreon: votre-username
# ko_fi: votre-username
# custom: ['https://votre-site.com/donate']
